In [1]:
import pandas as pd
import numpy as np

In [2]:
matches = pd.read_csv('/Users/tliu/Desktop/Erdos Project/Data/matches.csv')

In [3]:
matches.head()

player1         player2  score1  score2  best_of  tournament_id date  \
0  Colin Roscoe      Jackie Rea       9       6       17            753  NaN   
1  Tommy Murphy   Clive Everton       9       4       17            753  NaN   
2    Vic Harris     Marcus Owen       9       4       17            753  NaN   
3    Bob Harris  Graham Cripsey       9       6       17            753  NaN   
4  Geoff Foulds     Matt Gibson       9       3       17            753  NaN   

   year  
0  1982  
1  1982  
2  1982  
3  1982  
4  1982

In [4]:
tournaments = list(matches.tournament_id.unique())


In [5]:
matches[matches['tournament_id'] == tournaments[1040]]

player1           player2  score1  score2  best_of  \
111102        Xing Zihao    Fergal O'Brien       4       3        7   
111103        Cao Yupeng      David Lilley       4       2        7   
111104      Zhou Yuelong  Anthony Hamilton       4       0        7   
111105      Kyren Wilson   Mostafa Dorgham       4       2        7   
111106       Gary Wilson    Elliot Slessor       4       3        7   
...                  ...               ...     ...     ...      ...   
111222  Noppon Saengkham     Sanderson Lam       5       3        9   
111223      John Higgins          Tom Ford       5       3        9   
111224       Gary Wilson      Zhou Yuelong       6       5       11   
111225  Noppon Saengkham      John Higgins       6       3       11   
111226       Gary Wilson  Noppon Saengkham       9       5       17   

        tournament_id        date  year  
111102           5848  2023-11-02  2023  
111103           5848  2023-10-30  2023  
111104           5848  2023-10-30  2023  
111105           5848  2023-12-11  2023  
111106           5848  2023-12-11  2023  
...               ...         ...   ...  
111222           5848  2023-12-15  2023  
111223           5848  2023-12-15  2023  
111224           5848  2023-12-16  2023  
111225           5848  2023-12-16  2023  
111226           5848  2023-12-17  2023  

[125 rows x 8 columns]

In [6]:
#Using matches history before tornament xxxx to predict the results of tournament xxxx
from elo_v3 import elo_rating
from sklearn.metrics import mean_squared_error


#Ks represent K-factors we use
#nth means nth tournament among 1085 tournaments
Ks = [4, 6, 8, 15, 20]
nth = [750, 999, 1040, 1080]
scores = np.zeros((5,4))


i=0
for K in Ks:
    j=0
    for n in nth:
        past_tournaments = tournaments[:n]
        current = tournaments[n]
        past_index = matches['tournament_id'].map(lambda x: x in past_tournaments)
        

        matches_past = matches[past_index]
        matches_future = matches[matches['tournament_id'] == current]

        #Update statistics of players
        elo = elo_rating()
        elo.update_stats(matches = matches_past, K_factor = K, ratio = 0.1)

        #Store the actual result in y
        matches_future['result'] = 0  
        y = np.array(matches_future['result'])

        #Compute expected win_rate
        X = matches_future[['player1', 'player2', 'best_of']]
        _, expected = elo.predict(X)
        print(expected)

        #Compute the actual frame_rate
        actual = np.array(matches_future['score1']/(matches_future['score1']+matches_future['score2']))
        print(actual)

        #Record the accuracy score
        from sklearn.metrics import accuracy_score
        scores[i,j] = mean_squared_error(expected, actual)
        
        j += 1
    i+=1




/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.40914525 0.48001066 0.78329968 0.61004467 0.52622591 0.77902611
 0.38461624 0.56525075 0.8049462  0.19270945 0.8896823  0.17544764
 0.83889105 0.89934791 0.24277966 0.88795296 0.59025025 0.42372508
 0.81645321 0.58722369 0.93583612 0.24048908 0.39651675 0.6921095
 0.29317778 0.37460765 0.79616571 0.67480527 0.69264198 0.5168686
 0.87814715 0.5799334  0.55416165 0.239577   0.63760865 0.75676045
 0.87626214 0.73399752 0.79248994 0.88313927 0.83166869 0.626563
 0.29943286 0.60885457 0.71960437 0.46319171 0.81794705 0.35491586
 0.61360708 0.47751518 0.63818611 0.56340679 0.86442036 0.32027681
 0.7320405  0.24927176 0.64106741 0.51374653 0.53867261 0.83026408
 0.239577   0.35606144 0.84455265 0.65135486 0.67863372 0.81191475
 0.66707828 0.8519528  0.29317778 0.66429644 0.81115001 0.51998934
 0.8223718  0.75905399 0.8988944  0.47813895 0.77816418 0.30895699
 0.63529485 0.60408132 0.77729986 0.7407749  0.5926666  0.77381857
 0.7879312  0.27289178 0.61833804 0.65982175 0.18168098 0.74696679

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.35377194 0.65418811 0.70578503 0.42311474 0.75676045 0.66984852
 0.77206355 0.73643093 0.37812836 0.81943141 0.72161767 0.7422125
 0.58782954 0.59145898 0.52934125 0.93658263 0.47751518 0.44090253
 0.6165665  0.49562511 0.68568011 0.64164245 0.74507206 0.88442316
 0.52061331 0.89866696 0.77643314 0.4037173  0.54177737 0.42128514
 0.87380181 0.3062946  0.60228618 0.78117041 0.50312496 0.24277966
 0.37636637 0.77945617 0.61242094 0.34921308 0.85005086 0.58964548
 0.45078487 0.49437524 0.4329071  0.49687504 0.48001066 0.85875649
 0.76224005 0.7109495  0.41095957 0.58419052 0.78583498 0.42189477
 0.7378841  0.64221709 0.66984852 0.5093739  0.81229622 0.46132739
 0.82885017 0.88569476 0.33403307 0.76852478 0.42984097 0.69899148
 0.59447593 0.5670929  0.56032964 0.87653295 0.56340679 0.2630841
 0.58964548 0.52622591 0.49875    0.9022519  0.54549879 0.91548307
 0.39891212 0.66818777 0.61004467 0.32355107 0.63413559 0.71351147
 0.32849497 0.28597777 0.22140455 0.90114393 0.80178688 0.726114

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.34694389 0.62480647 0.58419052 0.88619999 0.58722369 0.64679939
 0.50187499 0.38284264 0.75996726 0.62831619 0.46816811 0.8049462
 0.91548307 0.54301838 0.80999843 0.55107127 0.74459692 0.7047457
 0.76087816 0.89934791 0.85226785 0.80845465 0.2120688  0.73056676
 0.68189626 0.67095333 0.60587367 0.86265277 0.87894741 0.54797694
 0.54735762 0.41156488 0.36760621 0.49437524 0.26551466 0.74554661
 0.33181223 0.47626785 0.15283974 0.46941324 0.72859384 0.61063923
 0.87380181 0.48562896 0.57932425 0.84520794 0.57871486 0.75996726
 0.65362233 0.7879312  0.45636131 0.60885457 0.30523324 0.34017825
 0.21458606 0.64737031 0.85226785 0.66262184 0.5112481  0.690509
 0.86932458 0.66541056 0.72061213 0.70109131 0.7716233  0.29007908
 0.72061213 0.47128164 0.67205626 0.71859439 0.74364489 0.54301838
 0.4139888  0.67590153 0.3224577  0.57871486 0.89041625 0.73302015
 0.4850045  0.20751006 0.41217046 0.86294871 0.60766317 0.38936077
 0.60766317 0.64964975 0.40854102 0.50812428 0.29110983 0.33292172

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.54363869 0.49562511 0.54425886 0.80099105 0.66150316 0.64622806
 0.61833804 0.54921513 0.73350912 0.44460335 0.60467908 0.57444252
 0.53432094 0.54549879 0.67644893 0.54425886 0.70630389 0.54611854
 0.50249998 0.69104301 0.73399752 0.57566435 0.45264238 0.53742985
 0.55848111 0.63413559 0.55045271 0.7422125  0.47003595 0.54115667
 0.48625347 0.63239379 0.39055022 0.3368195  0.75859646 0.78751316
 0.76133271 0.40191314 0.58782954 0.74173388 0.55539665 0.59568073
 0.64049195 0.64508414 0.61063923 0.49687504 0.45450121 0.57749537
 0.56770655 0.42372508 0.53991488 0.71707529 0.51811707 0.64164245
 0.60825903 0.48375572 0.69423634 0.7768668  0.35377194 0.52684915
 0.4906261  0.66206272 0.37402214 0.45264238 0.73302015 0.29995755
 0.67863372 0.20792148 0.59085475 0.50687457 0.72312181 0.54487889
 0.75813835 0.76852478 0.76087816 0.2748805  0.45574114 0.40974975
 0.48562896 0.57138398 0.63297478 0.6937054  0.6737071  0.52497919
 0.77381857 0.31918929 0.500625   0.70630389 0.55045271 0.3132

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.39174097 0.46194872 0.78876547 0.57749537 0.55477924 0.82090632
 0.35893259 0.53183189 0.83889105 0.15511942 0.91431521 0.1483628
 0.87599082 0.91871392 0.21627626 0.91490095 0.60766317 0.41520233
 0.85005086 0.58540457 0.95335849 0.21882959 0.37226784 0.70266065
 0.2748805  0.39293301 0.83271604 0.68081071 0.69264198 0.52248482
 0.90908388 0.60348325 0.52684915 0.18961711 0.63181242 0.79207852
 0.90158845 0.76224005 0.83375819 0.88770399 0.86932458 0.6159753
 0.27388502 0.62304666 0.74029454 0.49437524 0.82991147 0.33181223
 0.6479408  0.49500017 0.66429644 0.60348325 0.89543493 0.28444878
 0.76584563 0.21542996 0.6775423  0.55848111 0.53183189 0.86442036
 0.22356686 0.30364507 0.86847022 0.68836788 0.68783133 0.85383477
 0.6921095  0.85966375 0.24508501 0.62714777 0.81794705 0.53183189
 0.83201839 0.78625543 0.91011174 0.4725277  0.7879312  0.30682605
 0.63876318 0.62948311 0.77294226 0.76674106 0.61419964 0.764498
 0.81191475 0.2621159  0.65475346 0.67095333 0.15154943 0.74932208

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.32904667 0.64964975 0.72262098 0.42189477 0.77029895 0.6631805
 0.7904268  0.75767964 0.35606144 0.84090805 0.74029454 0.78287503
 0.62539235 0.62773216 0.52809537 0.94722505 0.47751518 0.44460335
 0.58175938 0.5        0.7320405  0.66485373 0.75445215 0.89330941
 0.53867261 0.91528943 0.80573004 0.37754067 0.53245431 0.38048268
 0.86761113 0.29369611 0.64279132 0.78625543 0.50562476 0.20020718
 0.33793728 0.81532661 0.60647049 0.33015148 0.85814894 0.55971365
 0.43967036 0.51624428 0.44954729 0.45946416 0.49375033 0.85538789
 0.75212911 0.72561752 0.39771382 0.58115096 0.78372374 0.41217046
 0.73350912 0.64679939 0.71504211 0.5124974  0.82164024 0.46505705
 0.84520794 0.90887704 0.31324327 0.78202392 0.42311474 0.68997448
 0.56647906 0.56340679 0.58540457 0.88000737 0.53618662 0.27587823
 0.64565631 0.56402164 0.51312199 0.91253598 0.49437524 0.91392268
 0.3840247  0.66206272 0.63760865 0.32739298 0.61479187 0.73154982
 0.33015148 0.29995755 0.21627626 0.90908388 0.80297611 0.71555

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.3362613  0.63760865 0.58540457 0.90443467 0.56831998 0.67863372
 0.500625   0.38461624 0.76269283 0.67535364 0.42494645 0.840238
 0.92290586 0.56647906 0.84683628 0.57932425 0.7879312  0.78031449
 0.77029895 0.91092647 0.89378501 0.84748368 0.17909368 0.79657113
 0.70526563 0.70056714 0.66763326 0.89543493 0.91031605 0.56525075
 0.58358312 0.39055022 0.39352951 0.49750002 0.28648853 0.74412119
 0.31864627 0.53307662 0.14185106 0.5168686  0.75306009 0.60168718
 0.88442316 0.53369884 0.61242094 0.86026588 0.53556484 0.77338072
 0.63529485 0.81682756 0.43474925 0.59145898 0.31270572 0.33793728
 0.22356686 0.690509   0.87435214 0.70161495 0.50812428 0.73885001
 0.89283193 0.66150316 0.7725032  0.6737071  0.79738015 0.27938787
 0.72908792 0.4893766  0.69423634 0.73154982 0.75026011 0.53805128
 0.42922839 0.6737071  0.32464636 0.59145898 0.91193552 0.79453805
 0.47502081 0.2120688  0.41156488 0.86674728 0.61479187 0.33292172
 0.58964548 0.66984852 0.41156488 0.500625   0.27239601 0.349781

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.58904043 0.52560259 0.56156107 0.82849523 0.70266065 0.6846015
 0.65982175 0.56647906 0.7768668  0.44151889 0.65869857 0.60647049
 0.55909747 0.52435571 0.69951723 0.58479767 0.74838172 0.549834
 0.51374653 0.70734001 0.764498   0.60048827 0.45326185 0.5621765
 0.53805128 0.68729428 0.5860112  0.78499229 0.46754569 0.5535439
 0.47315085 0.69104301 0.37226784 0.34637767 0.76539701 0.8241904
 0.80337133 0.39831282 0.61833804 0.75722034 0.57138398 0.64279132
 0.58843512 0.68729428 0.65418811 0.47751518 0.41277631 0.61833804
 0.60228618 0.450166   0.53742985 0.70318271 0.49812501 0.70004245
 0.57627492 0.53867261 0.66984852 0.79738015 0.35950805 0.53307662
 0.4887519  0.65869857 0.34637767 0.47938669 0.72462091 0.31593855
 0.71707529 0.19584004 0.59868766 0.51437104 0.71859439 0.56340679
 0.77816418 0.7904268  0.77643314 0.29369611 0.44460335 0.41459543
 0.53618662 0.63645254 0.66984852 0.6731573  0.70992092 0.53680829
 0.80767918 0.33737816 0.5274723  0.74696679 0.49187572 0.30100852
 

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.38107215 0.45264238 0.78583498 0.54735762 0.56893321 0.84520794
 0.3368195  0.49812501 0.85966375 0.13124447 0.92501348 0.13499471
 0.89775268 0.92874042 0.20505414 0.92956327 0.61242094 0.41702455
 0.86904032 0.56770655 0.96303079 0.21040266 0.35778291 0.70266065
 0.26551466 0.40914525 0.8547683  0.67863372 0.6791787  0.52871836
 0.9284088  0.62597786 0.50312496 0.16348817 0.61419964 0.81419467
 0.91372581 0.78329968 0.86026588 0.88619999 0.89041625 0.60108788
 0.2630841  0.63064853 0.7535247  0.52061331 0.82742692 0.32739298
 0.6731573  0.50999867 0.67972319 0.63181242 0.91193552 0.26551466
 0.78499229 0.19861073 0.69846522 0.59206293 0.52809537 0.88442316
 0.21458606 0.26551466 0.8794784  0.7109495  0.6937054  0.87680326
 0.70940582 0.85383477 0.21374457 0.58661758 0.82382786 0.54239794
 0.83341139 0.80573004 0.9162536  0.46505705 0.79125386 0.30735802
 0.64279132 0.64737031 0.7698563  0.78414719 0.62948311 0.7535247
 0.82599433 0.25826612 0.67972319 0.67150503 0.13853636 0.74932

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.3224577  0.62831619 0.72760399 0.42067575 0.77469249 0.64679939
 0.80376594 0.7698563  0.34581189 0.8519528  0.75537724 0.80297611
 0.65588284 0.64565631 0.52497919 0.9527995  0.47439741 0.4464561
 0.55230791 0.50562476 0.75491499 0.67480527 0.75859646 0.89798193
 0.55168967 0.92604733 0.82491373 0.36296921 0.51437104 0.34298954
 0.86732371 0.28394021 0.66596693 0.78457004 0.50812428 0.17186029
 0.31270572 0.83616964 0.60168718 0.32519473 0.85996508 0.52934125
 0.434135   0.53307662 0.47502081 0.43536371 0.49812501 0.84488058
 0.74932208 0.72958144 0.39711513 0.58843512 0.77945617 0.40011163
 0.7251195  0.65362233 0.74125468 0.51624428 0.82382786 0.47439741
 0.84941242 0.9227278  0.29317778 0.78959734 0.41641688 0.68352089
 0.54921513 0.5670929  0.59988837 0.88210326 0.52123721 0.28140561
 0.68189626 0.59326999 0.53369884 0.92019504 0.45884333 0.91173454
 0.37460765 0.65418811 0.65021855 0.32904667 0.59928816 0.74649398
 0.33403307 0.3268427  0.21290549 0.91193552 0.80376594 0.70785

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.33125818 0.64336515 0.5860112  0.9156763  0.56094545 0.70109131
 0.50437489 0.39651675 0.7640476  0.70889017 0.37695334 0.86146364
 0.93021522 0.57932425 0.86960831 0.60647049 0.81038289 0.82742692
 0.76763412 0.91945759 0.9162536  0.87185939 0.16043433 0.83582688
 0.72010853 0.71402223 0.72161767 0.91411915 0.9284088  0.57810523
 0.62010643 0.37812836 0.41702455 0.50374993 0.29890869 0.74743902
 0.30417394 0.57810523 0.14063813 0.55971365 0.76224005 0.5962827
 0.89235257 0.56647906 0.64106741 0.86789802 0.50999867 0.78414719
 0.61479187 0.83685344 0.42678023 0.58115096 0.3078905  0.32904667
 0.23460299 0.71605979 0.88695417 0.72111518 0.50749944 0.7698563
 0.90356684 0.65701046 0.80922774 0.65475346 0.81343708 0.2748805
 0.74029454 0.50187499 0.70682222 0.74507206 0.75026011 0.54053584
 0.43659321 0.67260702 0.3362613  0.60048827 0.92431689 0.82778361
 0.47502081 0.22530751 0.40793707 0.86500529 0.61951732 0.28444878
 0.57199613 0.69104301 0.42250463 0.49187572 0.2621159  0.3618138

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.62714777 0.55663096 0.57566435 0.83956567 0.72908792 0.70682222
 0.6846015  0.58115096 0.80019283 0.44522076 0.69793843 0.63064853
 0.58297545 0.49437524 0.70630389 0.62069519 0.78202392 0.54425886
 0.52809537 0.70785727 0.78329968 0.60766317 0.45822263 0.57871486
 0.51936531 0.73105858 0.61892785 0.81191475 0.46754569 0.56340679
 0.45822263 0.7349726  0.36876934 0.36239135 0.75905399 0.84290453
 0.82599433 0.40191314 0.63529485 0.764498   0.58175938 0.68406145
 0.53805128 0.70940582 0.69104301 0.45884333 0.37051689 0.64336515
 0.62245933 0.47876279 0.52622591 0.68135373 0.49687504 0.73885001
 0.55045271 0.59447593 0.64908052 0.81076675 0.37051689 0.53494295
 0.48375572 0.64336515 0.3307046  0.49562511 0.70889017 0.33737816
 0.73350912 0.18770378 0.60467908 0.51749286 0.71043548 0.57077161
 0.79535308 0.79535308 0.78372374 0.31163212 0.43843893 0.41580948
 0.56831998 0.6802672  0.70056714 0.64508414 0.7320405  0.549834
 0.8241904  0.34921308 0.55292599 0.76896922 0.44769209 0.295774

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.3520592  0.46132739 0.77029895 0.48438008 0.58115096 0.88795296
 0.29162601 0.41156488 0.89496585 0.08907353 0.94103299 0.11867895
 0.93583612 0.94453811 0.1974197  0.95445762 0.60228618 0.44460335
 0.89706217 0.47626785 0.97869962 0.21882959 0.33849684 0.6802672
 0.23325894 0.43229345 0.89283193 0.65362233 0.60527653 0.54921513
 0.96240267 0.68297985 0.45636131 0.13010847 0.53494295 0.86056613
 0.93070051 0.83821414 0.91470611 0.88053434 0.9244916  0.54921513
 0.25303321 0.65475346 0.77556401 0.57810523 0.80099105 0.36296921
 0.72161767 0.53120937 0.7047457  0.69317395 0.93702664 0.239577
 0.81794705 0.17544764 0.72362207 0.62363363 0.5149955  0.917964
 0.20261985 0.20181322 0.89912138 0.74507206 0.71555122 0.91372581
 0.74173388 0.82991147 0.16280553 0.48438008 0.85383477 0.57321977
 0.83375819 0.84716026 0.9310223  0.42555748 0.80019283 0.309491
 0.64964975 0.6791787  0.79412963 0.8306161  0.67260702 0.7422125
 0.85507837 0.239577   0.7280992  0.67699586 0.13238887 0.75629997
 0.

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.34411716 0.52497919 0.71960437 0.41884904 0.77859545 0.57260806
 0.83131841 0.79166649 0.34355313 0.86146364 0.79001237 0.82382786
 0.72908792 0.67535364 0.53183189 0.96285237 0.45884333 0.44707401
 0.4887519  0.52373215 0.77381857 0.66984852 0.76852478 0.90825398
 0.59507847 0.95234773 0.86789802 0.34807762 0.45388146 0.24232036
 0.88745453 0.26356907 0.7047457  0.7640476  0.5149955  0.12105259
 0.28090034 0.86529695 0.59326999 0.33015148 0.85320966 0.45512111
 0.41338242 0.55292599 0.57505355 0.38876653 0.49187572 0.80455338
 0.77118245 0.73981361 0.42311474 0.63529485 0.78457004 0.37930481
 0.70161495 0.67260702 0.77599888 0.52809537 0.81831902 0.52684915
 0.840238   0.94621626 0.25397941 0.79657113 0.40311562 0.66763326
 0.53991488 0.57015903 0.63529485 0.89496585 0.49312543 0.27788039
 0.74412119 0.66038267 0.6165665  0.94240503 0.39591868 0.91352852
 0.35148913 0.62187164 0.66094314 0.32794374 0.5621765  0.78751316
 0.34298954 0.43352094 0.20998763 0.9162536  0.81831902 0.7150

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.33181223 0.65362233 0.59507847 0.93583612 0.55848111 0.75398872
 0.5124974  0.46008512 0.7725032  0.78287503 0.26114999 0.89613508
 0.9527995  0.58115096 0.90929029 0.69317395 0.84941242 0.89979961
 0.73643093 0.93583612 0.9501452  0.9162536  0.13705129 0.89402211
 0.75859646 0.72462091 0.840238   0.94348103 0.95811339 0.60168718
 0.73007438 0.37402214 0.44707401 0.52622591 0.29162601 0.770741
 0.26649088 0.65588284 0.16520487 0.65475346 0.75905399 0.5799334
 0.91173454 0.65135486 0.71808858 0.88184302 0.4831314  0.82563471
 0.57321977 0.87129975 0.43843893 0.56402164 0.26894142 0.27938787
 0.2577875  0.75445215 0.90720705 0.73007438 0.5106234  0.83341139
 0.91606157 0.65362233 0.89259249 0.60048827 0.84057331 0.26259971
 0.78117041 0.53307662 0.72462091 0.78541394 0.75259489 0.59085475
 0.42067575 0.67644893 0.37812836 0.61182737 0.94505965 0.86146364
 0.51374653 0.27239601 0.37519353 0.84488058 0.65588284 0.17946152
 0.52809537 0.76359661 0.47377409 0.450166   0.23192025 0.3869858

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.71555122 0.64565631 0.60587367 0.84716026 0.76852478 0.75306009
 0.72760399 0.6212836  0.83131841 0.47876279 0.78457004 0.67205626
 0.65248946 0.40011163 0.69899148 0.69899148 0.8541465  0.51312199
 0.57749537 0.6637387  0.81532661 0.57688526 0.4906261  0.59568073
 0.47128164 0.8323675  0.70734001 0.85966375 0.46941324 0.58175938
 0.40131234 0.81757448 0.37226784 0.41338242 0.73545928 0.86086584
 0.8566205  0.42616874 0.64908052 0.78031449 0.59928816 0.77816418
 0.40251423 0.73056676 0.77643314 0.42311474 0.26697985 0.690509
 0.63760865 0.55786457 0.4831314  0.62069519 0.54921513 0.79166649
 0.5106234  0.73448534 0.61538376 0.83410441 0.4061269  0.53120937
 0.45450121 0.59988837 0.30842349 0.52186105 0.65926039 0.39831282
 0.73643093 0.166936   0.62304666 0.52560259 0.66038267 0.57566435
 0.84190885 0.77599888 0.79697594 0.35377194 0.44398611 0.40131234
 0.626563   0.77381857 0.77118245 0.55663096 0.76629364 0.57871486
 0.8516372  0.35950805 0.60408132 0.80297611 0.36760621 0.306826

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.3362613  0.47938669 0.76584563 0.46630116 0.58722369 0.90313029
 0.27737902 0.37460765 0.90636179 0.07395267 0.94846091 0.11405238
 0.95002664 0.94978873 0.19781611 0.96347326 0.59025025 0.46257015
 0.90572332 0.42678023 0.98432671 0.2359524  0.3368195  0.65926039
 0.20546195 0.43229345 0.90720705 0.63355538 0.55477924 0.5621765
 0.97333821 0.70889017 0.44336904 0.12185285 0.48001066 0.88105931
 0.93732104 0.86645828 0.93732104 0.8836543  0.93732104 0.51624428
 0.24973989 0.6802672  0.78414719 0.60348325 0.78876547 0.40131234
 0.74125468 0.52684915 0.71555122 0.72010853 0.94596124 0.23103078
 0.8306161  0.16486038 0.72211961 0.59928816 0.50374993 0.9310223
 0.19940776 0.19077226 0.90804545 0.7535247  0.73350912 0.92553205
 0.75259489 0.82920452 0.14647751 0.44090253 0.87380181 0.58904043
 0.83889105 0.86674728 0.94047563 0.39412633 0.81191475 0.31056055
 0.65021855 0.6921095  0.82527452 0.8575392  0.70109131 0.760423
 0.86818438 0.21755022 0.75212911 0.69317395 0.13499471 0.76763412

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.36644462 0.45822263 0.70682222 0.4200666  0.78457004 0.51998934
 0.83922865 0.79818678 0.35262969 0.86176173 0.80573004 0.823101
 0.75905399 0.69264198 0.55107127 0.96754791 0.45140389 0.44275215
 0.46879063 0.53058676 0.77338072 0.6631805  0.77988563 0.91451086
 0.62245933 0.96561019 0.89090318 0.35548845 0.42372508 0.19348851
 0.90443467 0.25397941 0.72412177 0.74838172 0.51811707 0.10479938
 0.27888482 0.87213843 0.59145898 0.33292172 0.84683628 0.42067575
 0.38639292 0.55601389 0.63645254 0.37285223 0.48687801 0.79001237
 0.79697594 0.75491499 0.43843893 0.66707828 0.8025803  0.38048268
 0.6921095  0.67644893 0.78074275 0.53618662 0.81607827 0.56770655
 0.82491373 0.95456617 0.24186165 0.79207852 0.39951173 0.65644687
 0.55230791 0.56402164 0.65869857 0.90699638 0.47689147 0.27239601
 0.770741   0.69635493 0.67260702 0.95434883 0.37812836 0.92074408
 0.33458944 0.60108788 0.66429644 0.32849497 0.54487889 0.81076675
 0.3520592  0.500625   0.21040266 0.92128966 0.83445006 0.739332

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.33961733 0.66262184 0.60706699 0.94374707 0.55786457 0.78202392
 0.50687457 0.5093739  0.78287503 0.81943141 0.22270014 0.90593657
 0.96417062 0.56279174 0.9234378  0.74269055 0.86875553 0.91945759
 0.71351147 0.94144779 0.95997873 0.93292416 0.13528691 0.91133134
 0.78329968 0.72561752 0.88288101 0.95324719 0.96809292 0.61063923
 0.78709451 0.38225213 0.44398611 0.53929381 0.27041856 0.78834863
 0.25445339 0.6775423  0.1974197  0.68621867 0.75119578 0.56279174
 0.92001126 0.69846522 0.75398872 0.88720459 0.48438008 0.85320966
 0.56647906 0.88339703 0.45698162 0.55971365 0.24323955 0.24601128
 0.26649088 0.76629364 0.9156763  0.71351147 0.51312199 0.86294871
 0.92019504 0.66038267 0.92757351 0.55601389 0.84586097 0.24973989
 0.80612106 0.55292599 0.72859384 0.80612106 0.75537724 0.63760865
 0.39532092 0.68297985 0.39532092 0.61538376 0.95154724 0.85936187
 0.55292599 0.29162601 0.34355313 0.82813971 0.68783133 0.1424608
 0.50624967 0.80651149 0.50312496 0.41763246 0.21500771 0.39532

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)


[0.75537724 0.68943945 0.61951732 0.84909236 0.7768668  0.77859545
 0.74364489 0.64164245 0.83821414 0.50812428 0.8241904  0.68352089
 0.68621867 0.35663485 0.69157651 0.72211961 0.88000737 0.49750002
 0.60885457 0.6165665  0.82742692 0.54239794 0.51811707 0.59326999
 0.44707401 0.87380181 0.7488522  0.87571899 0.47003595 0.58297545
 0.36066016 0.84716026 0.36935147 0.43843893 0.7369159  0.85845299
 0.86383331 0.43967036 0.6479408  0.79494586 0.60288487 0.81419467
 0.34242639 0.72661188 0.81038289 0.41459543 0.22970105 0.71300016
 0.63529485 0.58782954 0.46692338 0.60228618 0.59868766 0.8025803
 0.50687457 0.78959734 0.61004467 0.84323529 0.42250463 0.52809537
 0.43168002 0.58843512 0.30364507 0.53307662 0.64164245 0.42128514
 0.72760399 0.15348826 0.64049195 0.53494295 0.6159753  0.57871486
 0.86442036 0.75445215 0.80337133 0.37168381 0.46257015 0.3840247
 0.6479408  0.81191475 0.80218389 0.51811707 0.77816418 0.58297545
 0.86324411 0.3520592  0.6165665  0.81457258 0.34130143 0.320276

/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/2098003915.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


In [7]:
print(scores)

[[0.04511027 0.0497169  0.07126358 0.03380794]
 [0.04851583 0.05204659 0.07118478 0.03167362]
 [0.05098815 0.0539865  0.07163361 0.03100015]
 [0.05719899 0.05869029 0.07438659 0.03349601]
 [0.06065392 0.06133523 0.07678993 0.0366705 ]]


Ks = [4, 6, 8, 15, 20]
nth = [750, 999, 1040, 1080]

[[0.04511027 0.0497169  0.07126358 0.03380794]
 [0.04851583 0.05204659 0.07118478 0.03167362]
 [0.05098815 0.0539865  0.07163361 0.03100015]
 [0.05719899 0.05869029 0.07438659 0.03349601]
 [0.06065392 0.06133523 0.07678993 0.0366705 ]]

In [8]:
#Using matches history before tornament xxxx to predict the results of tournament xxxx
from elo_v3 import elo_rating
from sklearn.metrics import mean_squared_error


#Ks represent K-factors we use
#nth means nth tournament among 1085 tournaments
Ks = [2,3,5,7,8]
nth = [750, 999, 1040, 1080]
scores = np.zeros((5,4))


i=0
for K in Ks:
    j=0
    for n in nth:
        past_tournaments = tournaments[:n]
        current = tournaments[n]
        past_index = matches['tournament_id'].map(lambda x: x in past_tournaments)
        

        matches_past = matches[past_index]
        matches_future = matches[matches['tournament_id'] == current]

        #Update statistics of players
        elo = elo_rating()
        elo.update_stats(matches = matches_past, K_factor = K, ratio = 0.1)

        #Store the actual result in y
        matches_future['result'] = 0  
        y = np.array(matches_future['result'])

        #Compute expected win_rate
        X = matches_future[['player1', 'player2', 'best_of']]
        _, expected = elo.predict(X)
        print(expected)

        #Compute the actual frame_rate
        actual = np.array(matches_future['score1']/(matches_future['score1']+matches_future['score2']))
        print(actual)

        #Record the accuracy score
        from sklearn.metrics import accuracy_score
        scores[i,j] = mean_squared_error(expected, actual)
        
        j += 1
    i+=1




/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.44028635 0.50249998 0.7558389  0.62714777 0.48001066 0.68783133
 0.41763246 0.58661758 0.73154982 0.26697985 0.80999843 0.24554785
 0.76539701 0.84157582 0.31378133 0.81457258 0.54859611 0.44954729
 0.74173388 0.55724785 0.89425874 0.29890869 0.43967036 0.65531837
 0.34637767 0.38048268 0.72262098 0.65248946 0.65135486 0.5106234
 0.81038289 0.55107127 0.56831998 0.33849684 0.6159753  0.68675673
 0.8025803  0.67644893 0.71300016 0.8547683  0.74932208 0.61715736
 0.36354746 0.57260806 0.68890392 0.43597836 0.75859646 0.4139888
 0.56340679 0.46754569 0.58904043 0.50999867 0.78667527 0.39293301
 0.66038267 0.3208213  0.57688526 0.47439741 0.55168967 0.75398872
 0.2719008  0.42250463 0.76718789 0.58904043 0.66984852 0.71504211
 0.6212836  0.7904268  0.37285223 0.67972319 0.78031449 0.50749944
 0.77294226 0.7047457  0.86960831 0.4893766  0.7407749  0.32027681
 0.62480647 0.565865   0.75629997 0.67535364 0.54673815 0.7640476
 0.73056676 0.31431989 0.56279174 0.61419964 0.25874532 0.7201085

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.41884904 0.6165665  0.65362233 0.42800387 0.71197592 0.64106741
 0.73981361 0.68081071 0.42128514 0.76718789 0.68943945 0.65078692
 0.54549879 0.5149955  0.50812428 0.90378446 0.47315085 0.43905455
 0.64565631 0.5        0.59447593 0.59568073 0.70785727 0.86026588
 0.49375033 0.85538789 0.7109495  0.45512111 0.52871836 0.46319171
 0.87734233 0.3262929  0.53307662 0.75629997 0.500625   0.32464636
 0.42922839 0.70578503 0.61419964 0.4037173  0.82053848 0.59748577
 0.4831314  0.47190463 0.43229345 0.55786457 0.44769209 0.83889105
 0.76629364 0.65475346 0.44769209 0.59928816 0.76539701 0.42067575
 0.7251195  0.64164245 0.59085475 0.50687457 0.78031449 0.46754569
 0.76584563 0.83479513 0.35262969 0.72908792 0.43536371 0.70318271
 0.62069519 0.59447593 0.51998934 0.8566205  0.60766317 0.24880422
 0.50874911 0.47502081 0.49000133 0.87544664 0.61301418 0.90443467
 0.43536371 0.66818777 0.55416165 0.3208213  0.64622806 0.6846015
 0.35148913 0.31431989 0.22618143 0.87157983 0.78583498 0.72462

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.37460765 0.58904043 0.55848111 0.83956567 0.61123347 0.58964548
 0.51749286 0.40431927 0.74459692 0.55601389 0.4875026  0.73056676
 0.8972928  0.5093739  0.74173388 0.52310853 0.65078692 0.59326999
 0.71402223 0.87380181 0.75119578 0.73056676 0.28140561 0.62069519
 0.62889984 0.60587367 0.54239794 0.78918171 0.80767918 0.52871836
 0.51561992 0.44336904 0.36528458 0.49625007 0.25208934 0.7558389
 0.34017825 0.43229345 0.1873229  0.42189477 0.66094314 0.62363363
 0.84812884 0.40793707 0.54239794 0.80138927 0.63818611 0.72362207
 0.64049195 0.73885001 0.49625007 0.63123066 0.28292471 0.34355313
 0.22618143 0.57566435 0.80297611 0.58175938 0.51749286 0.60944978
 0.80099105 0.66206272 0.62889984 0.72859384 0.71197592 0.3307046
 0.70992092 0.4464561  0.63123066 0.70109131 0.69793843 0.54301838
 0.41035452 0.67095333 0.35491586 0.55724785 0.84488058 0.62831619
 0.50437489 0.23775995 0.41520233 0.83753494 0.57749537 0.45078487
 0.62187164 0.62714777 0.434135   0.5112481  0.34468163 0.317020

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.49812501 0.47626785 0.52310853 0.71859439 0.59928816 0.57260806
 0.54921513 0.52809537 0.64336515 0.45884333 0.52809537 0.53432094
 0.51312199 0.53805128 0.61242094 0.50749944 0.64508414 0.51998934
 0.49562511 0.63587389 0.68135373 0.52871836 0.46319171 0.50624967
 0.57932425 0.56954622 0.5168686  0.65926039 0.48625347 0.52622591
 0.49750002 0.55971365 0.44151889 0.35835755 0.70056714 0.70578503
 0.66874182 0.42678023 0.53556484 0.70266065 0.53556484 0.54301838
 0.67863372 0.5670929  0.55971365 0.50812428 0.47813895 0.50312496
 0.5124974  0.40673001 0.52061331 0.69741111 0.565865   0.56156107
 0.63006601 0.45512111 0.70630389 0.73643093 0.37754067 0.50374993
 0.4850045  0.62187164 0.42678023 0.42739194 0.70370424 0.309491
 0.60288487 0.23460299 0.57383126 0.48375572 0.70992092 0.49375033
 0.72958144 0.69793843 0.71146298 0.27289178 0.48125878 0.41459543
 0.40673001 0.46754569 0.58115096 0.68081071 0.61123347 0.51749286
 0.68514106 0.30895699 0.4850045  0.63064853 0.61063923 0.340739

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.42189477 0.49125089 0.77425583 0.62245933 0.50437489 0.74364489
 0.39891212 0.57871486 0.7768668  0.22226768 0.86265277 0.201009
 0.80884149 0.88000737 0.26894142 0.86235629 0.57260806 0.43352094
 0.78834863 0.57688526 0.92037844 0.26259971 0.41459543 0.67972319
 0.31216867 0.37051689 0.76718789 0.66763326 0.68081071 0.51374653
 0.85320966 0.5670929  0.56463629 0.28090034 0.63239379 0.72859384
 0.85100433 0.71146298 0.760423   0.87435214 0.79979282 0.626563
 0.32355107 0.59447593 0.70578503 0.44707401 0.798991   0.37812836
 0.59085475 0.47065875 0.61715736 0.53805128 0.83582688 0.35035025
 0.70318271 0.27737902 0.61301418 0.4906261  0.54487889 0.80099105
 0.25256098 0.38698582 0.81794705 0.62480647 0.6737071  0.77469249
 0.64908052 0.83375819 0.32739298 0.67699586 0.80297611 0.51374653
 0.80767918 0.73885001 0.88869699 0.4831314  0.76629364 0.31216867
 0.63239379 0.58722369 0.77425583 0.71758221 0.57444252 0.77294226
 0.76718789 0.28648853 0.59326999 0.64451155 0.21081829 0.74029454

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.37930481 0.64393856 0.68729428 0.42433565 0.74173388 0.6631805
 0.75951092 0.71656781 0.39651675 0.80019283 0.70889017 0.70630389
 0.56770655 0.55971365 0.52435571 0.92570418 0.47502081 0.43967036
 0.63297478 0.49625007 0.64679939 0.62187164 0.73350912 0.87599082
 0.5093739  0.8836543  0.75166274 0.42494645 0.53929381 0.44275215
 0.87787938 0.31431989 0.57077161 0.77294226 0.50125    0.27587823
 0.40131234 0.75072824 0.61538376 0.36993399 0.84057331 0.59988837
 0.46319171 0.48188293 0.42984097 0.52435571 0.46630116 0.8541465
 0.76807975 0.69157651 0.42555748 0.59145898 0.78159746 0.42311474
 0.73643093 0.64221709 0.63529485 0.50812428 0.80178688 0.46257015
 0.80845465 0.86645828 0.34298954 0.7558389  0.43229345 0.70370424
 0.61123347 0.57627492 0.54177737 0.87101915 0.58358312 0.25397941
 0.55107127 0.50312496 0.49375033 0.89354744 0.57810523 0.91352852
 0.41156488 0.66984852 0.58661758 0.32136628 0.64336515 0.70213807
 0.33347717 0.29059418 0.22400112 0.8913882  0.79858919 0.729581

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.35720868 0.61182737 0.57749537 0.86960831 0.60048827 0.62363363
 0.50687457 0.38876653 0.75537724 0.59568073 0.48250714 0.7768668
 0.90990701 0.52809537 0.78202392 0.53680829 0.70682222 0.65362233
 0.74554661 0.88992743 0.81457258 0.77816418 0.239577   0.68189626
 0.66150316 0.64451155 0.57321977 0.83479513 0.85226785 0.53867261
 0.53058676 0.42616874 0.35950805 0.49500017 0.25540308 0.75026011
 0.3362613  0.44892873 0.16486038 0.44522076 0.70370424 0.61774787
 0.86500529 0.45078487 0.56156107 0.83096754 0.60885457 0.74791066
 0.65531837 0.76763412 0.47377409 0.6212836  0.29473437 0.33905686
 0.21458606 0.61538376 0.83341139 0.62831619 0.51374653 0.65531837
 0.84553473 0.66541056 0.68297985 0.71707529 0.74979139 0.30258889
 0.71656781 0.45884333 0.65531837 0.7109495  0.73056676 0.54549879
 0.4073334  0.67644893 0.33125818 0.56954622 0.87297245 0.68729428
 0.49312543 0.21458606 0.41277631 0.85507837 0.59808686 0.4200666
 0.6165665  0.63876318 0.41641688 0.5106234  0.31002552 0.323004

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.51998934 0.48375572 0.53432094 0.7716233  0.63297478 0.61538376
 0.58782954 0.53929381 0.69635493 0.450166   0.56954622 0.55539665
 0.52310853 0.54735762 0.65248946 0.52435571 0.6791787  0.53680829
 0.49812501 0.67150503 0.71197592 0.55539665 0.45636131 0.52186105
 0.56831998 0.60348325 0.53307662 0.70889017 0.47564429 0.53432094
 0.49312543 0.59748577 0.41035452 0.34073961 0.7407749  0.7558389
 0.7251195  0.41035452 0.56402164 0.72710822 0.54487889 0.56893321
 0.6637387  0.61182737 0.5860112  0.50499983 0.47003595 0.54735762
 0.54177737 0.41277631 0.53369884 0.71555122 0.53805128 0.60348325
 0.62245933 0.46319171 0.70422523 0.76133271 0.35893259 0.51874122
 0.4893766  0.65078692 0.39651675 0.43720826 0.7280992  0.29943286
 0.64679939 0.21797608 0.58479767 0.49812501 0.72161767 0.52497919
 0.74602059 0.74364489 0.74412119 0.2679595  0.46505705 0.40793707
 0.450166   0.52560259 0.61004467 0.69529667 0.64679939 0.52123721
 0.7407749  0.31056055 0.4893766  0.67425643 0.58419052 0.32409

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.39951173 0.46941324 0.7879312  0.5938731  0.54301838 0.80337133
 0.37168381 0.54921513 0.82455236 0.17186029 0.90465054 0.15942669
 0.85996508 0.91072342 0.22661928 0.90378446 0.60108788 0.41763246
 0.83582688 0.58904043 0.94608889 0.22705774 0.38284264 0.69899148
 0.28191142 0.3834335  0.81682756 0.6791787  0.69582606 0.51998934
 0.89590216 0.59145898 0.54053584 0.21040266 0.63703079 0.7768668
 0.89163    0.74979139 0.81570274 0.88670326 0.85352249 0.62245933
 0.28394021 0.61715736 0.73105858 0.47938669 0.82671179 0.34017825
 0.63239379 0.48625347 0.65305611 0.58540457 0.88262226 0.29995755
 0.75166274 0.229259   0.66206272 0.53742985 0.53494295 0.85005086
 0.23058694 0.32794374 0.85936187 0.67260702 0.68352089 0.83651183
 0.68135373 0.85845299 0.26649088 0.64679939 0.81494989 0.52622591
 0.82920452 0.77381857 0.90550963 0.47502081 0.78457004 0.30735802
 0.63703079 0.61833804 0.77556401 0.75537724 0.60467908 0.77029895
 0.80178688 0.26600248 0.63818611 0.66707828 0.16314656 0.74885

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.33793728 0.65531837 0.71656781 0.42189477 0.76539701 0.66874182
 0.78202392 0.7488522  0.36528458 0.83201839 0.73154982 0.76629364
 0.60706699 0.61301418 0.52996405 0.94294542 0.47751518 0.44275215
 0.59928816 0.49687504 0.71300016 0.65531837 0.75119578 0.88943669
 0.53058676 0.90825398 0.79290076 0.38876653 0.53867261 0.40131234
 0.87017421 0.29943286 0.62539235 0.78499229 0.50437489 0.21925725
 0.35606144 0.79979282 0.60944978 0.33737816 0.85538789 0.57566435
 0.44336904 0.50624967 0.43905455 0.47502081 0.4887519  0.85845299
 0.75629997 0.72061213 0.40191314 0.58115096 0.78541394 0.41763246
 0.73594539 0.64393856 0.69582606 0.5112481  0.81831902 0.46194872
 0.83922865 0.89912138 0.32409847 0.7768668  0.42616874 0.69423634
 0.57932425 0.56340679 0.57444252 0.87894741 0.54797694 0.27041856
 0.62069519 0.54611854 0.50499983 0.90804545 0.51749286 0.9150954
 0.38995533 0.66541056 0.62714777 0.32574357 0.62422023 0.72362207
 0.32849497 0.29007908 0.21882959 0.90636179 0.8025803  0.72061

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.34073961 0.63239379 0.58540457 0.89683109 0.57566435 0.66429644
 0.500625   0.38166196 0.76178668 0.65418811 0.44831033 0.82491373
 0.91945759 0.55663096 0.8306161  0.56525075 0.77029895 0.74649398
 0.76763412 0.90572332 0.87680326 0.83026408 0.19348851 0.76807975
 0.69529667 0.68890392 0.63760865 0.88184302 0.89683109 0.55663096
 0.56463629 0.39951173 0.38048268 0.49562511 0.27687819 0.74364489
 0.32519473 0.50562476 0.1458535  0.49312543 0.74364489 0.60527653
 0.87974314 0.5124974  0.5962827  0.8541465  0.55416165 0.76763412
 0.64622806 0.80415996 0.44336904 0.59928816 0.31109608 0.33961733
 0.21797608 0.67205626 0.86529695 0.68514106 0.5093739  0.71707529
 0.88339703 0.6637387  0.7488522  0.68675673 0.78625543 0.28343219
 0.72462091 0.48188293 0.6846015  0.7251195  0.7488522  0.53991488
 0.42189477 0.67480527 0.32191175 0.5860112  0.90269198 0.76852478
 0.47876279 0.20792148 0.41217046 0.86616874 0.61182737 0.3600839
 0.59868766 0.65982175 0.40854102 0.50499983 0.27989147 0.34186

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.5670929  0.50999867 0.5535439  0.81794705 0.6846015  0.66818777
 0.64164245 0.55848111 0.75859646 0.44275215 0.63413559 0.59206293
 0.54673815 0.53680829 0.69104301 0.56463629 0.72859384 0.549834
 0.50749944 0.70213807 0.75119578 0.59025025 0.45202306 0.55045271
 0.54797694 0.66206272 0.56831998 0.76629364 0.46816811 0.54797694
 0.48001066 0.6637387  0.37930481 0.34017825 0.7649478  0.80884149
 0.78583498 0.39831282 0.60527653 0.75119578 0.56402164 0.62010643
 0.61479187 0.6692954  0.63355538 0.4875026  0.43474925 0.60108788
 0.58722369 0.43597836 0.53991488 0.71197592 0.50499983 0.67425643
 0.59206293 0.5106234  0.68135373 0.78834863 0.35548845 0.53058676
 0.49000133 0.6631805  0.35835755 0.46754569 0.73056676 0.30682605
 0.70161495 0.201009   0.59568073 0.5124974  0.72161767 0.55601389
 0.76852478 0.78244978 0.77029895 0.28394021 0.44954729 0.41217046
 0.51437104 0.60766317 0.65248946 0.68514106 0.69423634 0.53058676
 0.79412963 0.32849497 0.51374653 0.72958144 0.51936531 0.306294

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.38639292 0.45636131 0.78751316 0.56156107 0.56340679 0.83445006
 0.34751054 0.51437104 0.85036924 0.14215566 0.92056145 0.14063813
 0.88820145 0.9244916  0.2095732  0.92308355 0.61123347 0.41459543
 0.86086584 0.57810523 0.9588101  0.21374457 0.36412611 0.70318271
 0.26992562 0.40191314 0.84455265 0.6802672  0.68729428 0.52497919
 0.91982709 0.61479187 0.51437104 0.17436529 0.62422023 0.80415996
 0.90846209 0.77338072 0.84812884 0.88745453 0.88132105 0.60885457
 0.26746939 0.62773216 0.74791066 0.50812428 0.82991147 0.32794374
 0.66150316 0.50249998 0.6731573  0.61892785 0.90465054 0.27338812
 0.7768668  0.20546195 0.68943945 0.57688526 0.52934125 0.87571899
 0.21840254 0.28292471 0.87490042 0.70109131 0.690509   0.86674728
 0.70161495 0.8575392  0.22793645 0.60706699 0.82053848 0.53680829
 0.833064   0.79657113 0.91333083 0.46879063 0.79001237 0.30682605
 0.64049195 0.63876318 0.77118245 0.77599888 0.62245933 0.75905399
 0.81980102 0.25970546 0.66874182 0.67205626 0.14368683 0.7488

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.32464636 0.6399161  0.72561752 0.42067575 0.77294226 0.65531837
 0.79738015 0.764498   0.34978145 0.84716026 0.74791066 0.79494586
 0.64164245 0.63818611 0.52684915 0.95026349 0.47626785 0.44583835
 0.56647906 0.50312496 0.74554661 0.67095333 0.75676045 0.89590216
 0.54549879 0.92092632 0.81607827 0.36876934 0.52435571 0.36181389
 0.86674728 0.28802408 0.65588284 0.78583498 0.50687457 0.18429726
 0.32409847 0.82706965 0.60408132 0.3268427  0.85966375 0.54425886
 0.43659321 0.52560259 0.46132739 0.44522076 0.49687504 0.85036924
 0.74979139 0.72859384 0.39651675 0.58419052 0.78117041 0.4061269
 0.72958144 0.65021855 0.73007438 0.51437104 0.823101   0.46941324
 0.84812884 0.91663647 0.30258889 0.78625543 0.4194577  0.68621867
 0.55663096 0.56463629 0.59326999 0.88079708 0.52809537 0.27938787
 0.66596693 0.57932425 0.52310853 0.91644523 0.47502081 0.91273531
 0.37812836 0.65813632 0.64508414 0.32849497 0.60647049 0.73981361
 0.33236674 0.31270572 0.21416502 0.91072342 0.80297611 0.71094

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.33347717 0.64106741 0.58540457 0.91072342 0.56402164 0.690509
 0.50187499 0.38936077 0.76314502 0.6937054  0.40071184 0.8519528
 0.92655932 0.57383126 0.85936187 0.59326999 0.80099105 0.80612106
 0.7698563  0.91548307 0.90657375 0.86086584 0.16833131 0.81869041
 0.71351147 0.70889017 0.69582606 0.90593657 0.92037844 0.57138398
 0.60228618 0.38284264 0.4061269  0.5        0.29369611 0.74554661
 0.31163212 0.55724785 0.14033625 0.53929381 0.75905399 0.59868766
 0.88844946 0.55107127 0.62714777 0.86471309 0.52061331 0.77859545
 0.62480647 0.82778361 0.42984097 0.5860112  0.31109608 0.33458944
 0.229259   0.70526563 0.88158228 0.71351147 0.50749944 0.7558389
 0.8988944  0.65926039 0.79207852 0.6637387  0.80612106 0.27687819
 0.73448534 0.49625007 0.70161495 0.7378841  0.75072824 0.53805128
 0.434135   0.6731573  0.32959884 0.59688438 0.91890042 0.81343708
 0.47439741 0.21797608 0.40974975 0.86645828 0.6165665  0.30735802
 0.5805423  0.6802672  0.41641688 0.49625007 0.26697985 0.35663485

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.60885457 0.54115667 0.56893321 0.83513962 0.71707529 0.69635493
 0.6737071  0.57444252 0.79001237 0.44336904 0.67972319 0.61951732
 0.57138398 0.5093739  0.70370424 0.60348325 0.76584563 0.54735762
 0.52061331 0.70889017 0.77512855 0.60587367 0.45512111 0.57138398
 0.52871836 0.71043548 0.60288487 0.79939221 0.46754569 0.55909747
 0.46567906 0.71504211 0.36993399 0.35377194 0.76269283 0.83479513
 0.81607827 0.39891212 0.62831619 0.76133271 0.57688526 0.66485373
 0.56279174 0.70004245 0.6737071  0.46754569 0.39114543 0.63181242
 0.61360708 0.46443516 0.53183189 0.6921095  0.49625007 0.72161767
 0.56279174 0.5670929  0.65869857 0.80455338 0.36470515 0.53494295
 0.48625347 0.65135486 0.33737816 0.4887519  0.71707529 0.3262929
 0.72710822 0.19115851 0.60168718 0.51624428 0.71504211 0.56770655
 0.78709451 0.79412963 0.78074275 0.30311672 0.44090253 0.41580948
 0.55416165 0.65982175 0.68568011 0.65926039 0.72211961 0.54301838
 0.81682756 0.34355313 0.54115667 0.75905399 0.46754569 0.29786

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.38107215 0.45264238 0.78583498 0.54735762 0.56893321 0.84520794
 0.3368195  0.49812501 0.85966375 0.13124447 0.92501348 0.13499471
 0.89775268 0.92874042 0.20505414 0.92956327 0.61242094 0.41702455
 0.86904032 0.56770655 0.96303079 0.21040266 0.35778291 0.70266065
 0.26551466 0.40914525 0.8547683  0.67863372 0.6791787  0.52871836
 0.9284088  0.62597786 0.50312496 0.16348817 0.61419964 0.81419467
 0.91372581 0.78329968 0.86026588 0.88619999 0.89041625 0.60108788
 0.2630841  0.63064853 0.7535247  0.52061331 0.82742692 0.32739298
 0.6731573  0.50999867 0.67972319 0.63181242 0.91193552 0.26551466
 0.78499229 0.19861073 0.69846522 0.59206293 0.52809537 0.88442316
 0.21458606 0.26551466 0.8794784  0.7109495  0.6937054  0.87680326
 0.70940582 0.85383477 0.21374457 0.58661758 0.82382786 0.54239794
 0.83341139 0.80573004 0.9162536  0.46505705 0.79125386 0.30735802
 0.64279132 0.64737031 0.7698563  0.78414719 0.62948311 0.7535247
 0.82599433 0.25826612 0.67972319 0.67150503 0.13853636 0.74932

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.3224577  0.62831619 0.72760399 0.42067575 0.77469249 0.64679939
 0.80376594 0.7698563  0.34581189 0.8519528  0.75537724 0.80297611
 0.65588284 0.64565631 0.52497919 0.9527995  0.47439741 0.4464561
 0.55230791 0.50562476 0.75491499 0.67480527 0.75859646 0.89798193
 0.55168967 0.92604733 0.82491373 0.36296921 0.51437104 0.34298954
 0.86732371 0.28394021 0.66596693 0.78457004 0.50812428 0.17186029
 0.31270572 0.83616964 0.60168718 0.32519473 0.85996508 0.52934125
 0.434135   0.53307662 0.47502081 0.43536371 0.49812501 0.84488058
 0.74932208 0.72958144 0.39711513 0.58843512 0.77945617 0.40011163
 0.7251195  0.65362233 0.74125468 0.51624428 0.82382786 0.47439741
 0.84941242 0.9227278  0.29317778 0.78959734 0.41641688 0.68352089
 0.54921513 0.5670929  0.59988837 0.88210326 0.52123721 0.28140561
 0.68189626 0.59326999 0.53369884 0.92019504 0.45884333 0.91173454
 0.37460765 0.65418811 0.65021855 0.32904667 0.59928816 0.74649398
 0.33403307 0.3268427  0.21290549 0.91193552 0.80376594 0.70785

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


[0.33125818 0.64336515 0.5860112  0.9156763  0.56094545 0.70109131
 0.50437489 0.39651675 0.7640476  0.70889017 0.37695334 0.86146364
 0.93021522 0.57932425 0.86960831 0.60647049 0.81038289 0.82742692
 0.76763412 0.91945759 0.9162536  0.87185939 0.16043433 0.83582688
 0.72010853 0.71402223 0.72161767 0.91411915 0.9284088  0.57810523
 0.62010643 0.37812836 0.41702455 0.50374993 0.29890869 0.74743902
 0.30417394 0.57810523 0.14063813 0.55971365 0.76224005 0.5962827
 0.89235257 0.56647906 0.64106741 0.86789802 0.50999867 0.78414719
 0.61479187 0.83685344 0.42678023 0.58115096 0.3078905  0.32904667
 0.23460299 0.71605979 0.88695417 0.72111518 0.50749944 0.7698563
 0.90356684 0.65701046 0.80922774 0.65475346 0.81343708 0.2748805
 0.74029454 0.50187499 0.70682222 0.74507206 0.75026011 0.54053584
 0.43659321 0.67260702 0.3362613  0.60048827 0.92431689 0.82778361
 0.47502081 0.22530751 0.40793707 0.86500529 0.61951732 0.28444878
 0.57199613 0.69104301 0.42250463 0.49187572 0.2621159  0.3618138

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v3/elo_v3.py:120: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)


[0.62714777 0.55663096 0.57566435 0.83956567 0.72908792 0.70682222
 0.6846015  0.58115096 0.80019283 0.44522076 0.69793843 0.63064853
 0.58297545 0.49437524 0.70630389 0.62069519 0.78202392 0.54425886
 0.52809537 0.70785727 0.78329968 0.60766317 0.45822263 0.57871486
 0.51936531 0.73105858 0.61892785 0.81191475 0.46754569 0.56340679
 0.45822263 0.7349726  0.36876934 0.36239135 0.75905399 0.84290453
 0.82599433 0.40191314 0.63529485 0.764498   0.58175938 0.68406145
 0.53805128 0.70940582 0.69104301 0.45884333 0.37051689 0.64336515
 0.62245933 0.47876279 0.52622591 0.68135373 0.49687504 0.73885001
 0.55045271 0.59447593 0.64908052 0.81076675 0.37051689 0.53494295
 0.48375572 0.64336515 0.3307046  0.49562511 0.70889017 0.33737816
 0.73350912 0.18770378 0.60467908 0.51749286 0.71043548 0.57077161
 0.79535308 0.79535308 0.78372374 0.31163212 0.43843893 0.41580948
 0.56831998 0.6802672  0.70056714 0.64508414 0.7320405  0.549834
 0.8241904  0.34921308 0.55292599 0.76896922 0.44769209 0.295774

/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1958/711043284.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future['result'] = 0


In [9]:
print(scores)

[[0.04081901 0.04758738 0.07280416 0.03812379]
 [0.042967   0.04850241 0.07176707 0.035694  ]
 [0.04693483 0.05093644 0.07112929 0.03248546]
 [0.04983187 0.05306772 0.07137247 0.03119329]
 [0.05098815 0.0539865  0.07163361 0.03100015]]


Ks = [2,3,5,7,8]
nth = [750, 999, 1040, 1080]

Ks = [4, 6, 8, 15, 20]
nth = [750, 999, 1040, 1080]

[[0.04081901 0.04758738 0.07280416 0.03812379]
 [0.042967   0.04850241 0.07176707 0.035694  ]
 [0.04693483 0.05093644 0.07112929 0.03248546]
 [0.04983187 0.05306772 0.07137247 0.03119329]
 [0.05098815 0.0539865  0.07163361 0.03100015]]

 [[0.04511027 0.0497169  0.07126358 0.03380794]
 [0.04851583 0.05204659 0.07118478 0.03167362]
 [0.05098815 0.0539865  0.07163361 0.03100015]
 [0.05719899 0.05869029 0.07438659 0.03349601]
 [0.06065392 0.06133523 0.07678993 0.0366705 ]]

In [14]:
scores2 = np.array(
[[0.04511027, 0.0497169,  0.07126358, 0.03380794],
 [0.04851583, 0.05204659, 0.07118478, 0.03167362],
 [0.05098815, 0.0539865,  0.07163361, 0.03100015],
 [0.05719899, 0.05869029, 0.07438659, 0.03349601],
 [0.06065392, 0.06133523, 0.07678993, 0.0366705 ]]
 )

In [41]:
scores1 = scores
scores1

array([[0.04081901, 0.04758738, 0.07280416, 0.03812379],
       [0.042967  , 0.04850241, 0.07176707, 0.035694  ],
       [0.04693483, 0.05093644, 0.07112929, 0.03248546],
       [0.04983187, 0.05306772, 0.07137247, 0.03119329],
       [0.05098815, 0.0539865 , 0.07163361, 0.03100015]])

In [42]:
scores_df = pd.concat([pd.DataFrame(scores1), pd.DataFrame(scores2)])

In [43]:
scores_df['K-factor'] = [2,3,5,7,8, 4, 6, 8, 15, 20]

In [44]:
scores_df.set_index('K-factor', inplace=True)

In [46]:
scores_df.rename(columns = {
    0: 750,
    1: 999,
    2: 1040,
    3: 1080
})

750       999       1040      1080
K-factor                                        
2         0.040819  0.047587  0.072804  0.038124
3         0.042967  0.048502  0.071767  0.035694
5         0.046935  0.050936  0.071129  0.032485
7         0.049832  0.053068  0.071372  0.031193
8         0.050988  0.053987  0.071634  0.031000
4         0.045110  0.049717  0.071264  0.033808
6         0.048516  0.052047  0.071185  0.031674
8         0.050988  0.053986  0.071634  0.031000
15        0.057199  0.058690  0.074387  0.033496
20        0.060654  0.061335  0.076790  0.036671

In [47]:
average_score = scores_df.mean(axis=1)
average_score

K-factor
2     0.049834
3     0.049733
5     0.050372
7     0.051366
8     0.051902
4     0.049975
6     0.050855
8     0.051902
15    0.055943
20    0.058862
dtype: float64